language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository --yes ppa:zoogie/sdl2-snapshots
  - sudo apt-get update -qq
  - sudo apt-get install -y git libsdl1.2-dev libsdl2-dev libboost-filesystem1.48-dev libboost-system1.48-dev libgl1-mesa-dev libpng-dev pkg-config zlib1g-dev
  - git clone --depth=1 --branch=master git://github.com/mupen64plus/mupen64plus-core.git deps/mupen64plus-core
env:
 - HIRES=0 TXCDXTN=0 NO_ASM=0
 - HIRES=0 TXCDXTN=0 NO_ASM=1
 - HIRES=0 TXCDXTN=1 NO_ASM=0
 - HIRES=0 TXCDXTN=1 NO_ASM=1
 - HIRES=1 TXCDXTN=0 NO_ASM=0
 - HIRES=1 TXCDXTN=0 NO_ASM=1
 - HIRES=1 TXCDXTN=1 NO_ASM=0
 - HIRES=1 TXCDXTN=1 NO_ASM=1
script:
 - make -C projects/unix APIDIR="$(pwd)/deps/mupen64plus-core/src/api/" V=1 clean && CPPFLAGS="-D__extern_always_inline=inline" LDFLAGS="-Wl,--no-add-needed -Wl,--no-undefined" OPTFLAGS="-O2" make SDL_CONFIG=sdl-config CC="${CC}" CXX="${CXX}" -j$(nproc) -C projects/unix APIDIR="$(pwd)/deps/mupen64plus-core/src/api/" V=1 all
 - make -C projects/unix APIDIR="$(pwd)/deps/mupen64plus-core/src/api/" V=1 clean && CPPFLAGS="-D__extern_always_inline=inline" LDFLAGS="-Wl,--no-add-needed -Wl,--no-undefined" OPTFLAGS="-O2" make SDL_CONFIG=sdl2-config CC="${CC}" CXX="${CXX}" -j$(nproc) -C projects/unix APIDIR="$(pwd)/deps/mupen64plus-core/src/api/" V=1 all
